import type { Locale, LocalizedString } from '../i18n/types'

export type { Locale, LocalizedString }

export interface ProjectImage {
  src: string
  width: number
  height: number
}

export interface Project {
  id: string
  slug: string
  title: LocalizedString
  summary: LocalizedString
  description: LocalizedString
  category: LocalizedString
  categories: LocalizedString[]
  year: number
  client?: string
  role: LocalizedString
  cover: ProjectImage
  coverAlt: LocalizedString
  gallery: ProjectImage[]
  links?: { live?: string; repo?: string; caseStudy?: string }
  featured: boolean
}

// Generated by scripts/import-portfolio-content.mjs — edit that script, not this file.
export const projects: Project[] = [
  {
    id: "vitrina",
    slug: "vitrina",
    title: { en: "Vitrina", es: "Vitrina" },
    summary: { en: "An open-source React library for draggable, zoomable planes of objects.", es: "Librería React de código abierto: planos de objetos arrastrables y con zoom." },
    description: { en: "An open-source React library I wrote and published to npm: a finite, draggable plane of cut-out objects — pan with inertia and elastic edges, discrete zoom, a staggered reveal as objects enter the frame, a grid view the objects Flip into, and a detail panel one object flies into while the plane stays alive beside it. It renders on the server — positions are deterministic from a seed, so hydration matches — ships no copy and no default language (every string arrives through a labels prop), and keeps GSAP as a peer dependency so its ~21 KB stays off the critical path. MIT-licensed, and running in production on Mediterra.", es: "Una librería de React open source que escribí y publiqué en npm: un plano finito y arrastrable de objetos recortados — pan con inercia y bordes elásticos, zoom discreto, un reveal escalonado conforme los objetos entran en cuadro, una vista de cuadrícula a la que los objetos hacen Flip, y un panel de detalle al que un objeto vuela mientras el plano sigue vivo a un lado. Renderiza en servidor — las posiciones son deterministas a partir de un seed, así que la hidratación coincide —, no trae copy ni idioma por defecto (cada string llega por la prop labels) y mantiene GSAP como peer dependency para que sus ~21 KB queden fuera del critical path. Licencia MIT, y en producción en Mediterra." },
    category: { en: "Open Source Library", es: "Librería Open Source" },
    categories: [
      { en: "React", es: "React" },
      { en: "TypeScript", es: "TypeScript" },
      { en: "GSAP", es: "GSAP" },
      { en: "npm", es: "npm" },
      { en: "Open Source", es: "Open Source" },
    ],
    year: 2026,
    role: { en: "Author / Maintainer", es: "Autor / Mantenedor" },
    cover: { src: "/projects/vitrina-detail.webp", width: 1280, height: 746 },
    coverAlt: { en: "Vitrina's detail panel open on the left showing a product's full detail while the draggable plane of cut-out bottles stays interactive on the right", es: "Panel de detalle de Vitrina abierto a la izquierda con el detalle completo de un producto mientras el plano arrastrable de botes recortados sigue interactivo a la derecha" },
    gallery: [
      { src: "/projects/vitrina-detail.webp", width: 1280, height: 746 },
      { src: "/projects/vitrina-plane.webp", width: 1280, height: 746 },
      { src: "/projects/vitrina-npm.webp", width: 1280, height: 636 },
    ],
    links: { live: "https://www.npmjs.com/package/vitrina", repo: "https://github.com/MikeAlvarado/vitrina" },
    featured: true,
  },
  {
    id: "mediterra",
    slug: "mediterra",
    title: { en: "Mediterra", es: "Mediterra" },
    summary: { en: "A bilingual editorial site for a preventive-medicine practice in Monterrey.", es: "Sitio editorial bilingüe para un consultorio de medicina preventiva en Monterrey." },
    description: { en: "I designed and built Mediterra, the site for Dr. Andrea's preventive-medicine practice in Monterrey — an editorial, bilingual site (ES/EN) covering the method, the consultation, and a supplement catalog, server-rendered with React Router and Vite. The shop is not a list: it is a draggable plane of cut-out products you pan and zoom through, and opening one flies it into a detail panel while the plane stays alive beside it. That whole interaction runs on Vitrina, the React library I wrote for it.", es: "Diseñé y construí Mediterra, el sitio de la consulta de medicina preventiva de la Dra. Andrea en Monterrey — un sitio editorial y bilingüe (ES/EN) que cubre el método, la consulta y un catálogo de suplementos, renderizado en servidor con React Router y Vite. La tienda no es una lista: es un plano arrastrable de productos recortados por el que navegas con pan y zoom, y al abrir uno vuela hacia un panel de detalle mientras el plano sigue vivo a un lado. Toda esa interacción corre sobre Vitrina, la librería de React que escribí para eso." },
    category: { en: "Clinic Website", es: "Sitio de Clínica" },
    categories: [
      { en: "React", es: "React" },
      { en: "React Router", es: "React Router" },
      { en: "GSAP", es: "GSAP" },
      { en: "Vitrina", es: "Vitrina" },
      { en: "Firebase Hosting", es: "Firebase Hosting" },
    ],
    year: 2026,
    role: { en: "Design & Development", es: "Diseño y Desarrollo" },
    cover: { src: "/projects/mediterra-hero.webp", width: 1280, height: 746 },
    coverAlt: { en: "Mediterra homepage hero in cream and deep green with the headline 'Preventive medicine, with time to listen'", es: "Hero de la página principal de Mediterra en crema y verde profundo con el titular 'Preventive medicine, with time to listen'" },
    gallery: [
      { src: "/projects/mediterra-hero.webp", width: 1280, height: 746 },
      { src: "/projects/mediterra-shop.webp", width: 1280, height: 746 },
    ],
    links: { live: "https://mediterra-mx.web.app/" },
    featured: true,
  },
  {
    id: "aiMeter",
    slug: "ai-meter",
    title: { en: "AIMeter", es: "AIMeter" },
    summary: { en: "A native iOS and macOS app for tracking AI usage and limits.", es: "App nativa de iOS y macOS para monitorear uso y límites de IA." },
    description: { en: "I built AIMeter, an open-source iOS and macOS app that surfaces your Claude usage limits at a glance — home screen and lock screen widgets, a macOS menu bar item, and optional reset notifications, with session, weekly, and top-model-weekly windows. It's pure SwiftUI with no server involved: your token stays in the Keychain on-device.", es: "Construí AIMeter, una app open-source para iOS y macOS que muestra tus límites de uso de Claude de un vistazo — widgets para pantalla de inicio y de bloqueo, un ícono en la barra de menú de macOS y notificaciones opcionales de reinicio, con ventanas de sesión, semanal y semanal del modelo top. Es 100% SwiftUI sin servidor de por medio: tu token se queda en el Keychain, en tu dispositivo." },
    category: { en: "iOS & macOS App", es: "App iOS y macOS" },
    categories: [
      { en: "Swift", es: "Swift" },
      { en: "SwiftUI", es: "SwiftUI" },
      { en: "iOS", es: "iOS" },
      { en: "macOS", es: "macOS" },
    ],
    year: 2026,
    role: { en: "Creator / Engineer", es: "Creador / Ingeniero" },
    cover: { src: "/projects/aimeter-launch.webp", width: 3200, height: 1800 },
    coverAlt: { en: "AIMeter launch graphic showing iPhone home screen widgets with Claude usage percentages next to the AIMeter wordmark", es: "Gráfico de lanzamiento de AIMeter mostrando los widgets de pantalla de inicio del iPhone con los porcentajes de uso de Claude junto al logotipo de AIMeter" },
    gallery: [
      { src: "/projects/aimeter-launch.webp", width: 3200, height: 1800 },
      { src: "/projects/aimeter-widget.webp", width: 1206, height: 994 },
    ],
    links: { repo: "https://github.com/MikeAlvarado/AIMeter" },
    featured: true,
  },
  {
    id: "koddaStudio",
    slug: "kodda-studio",
    title: { en: "Kodda +Studio", es: "Kodda +Studio" },
    summary: { en: "The product I co-founded and led from CTO to CEO, on the App Store.", es: "El producto que cofundé y dirigí de CTO a CEO, publicado en la App Store." },
    description: { en: "Led Kodda through its evolution into a hybrid wellness platform combining digital programs with access to top fitness studios in Monterrey. Designed and shipped the reservation system, class credits logic, waitlists, cancellations, gifting, event activations, and studio onboarding tools. Scaled the platform from 30 to 400+ users in its first months. Oversaw product, engineering, partnerships, and community growth as CEO.", es: "Lideré la evolución de Kodda hacia una plataforma híbrida de bienestar que combina programas digitales con acceso a los mejores estudios fitness de Monterrey. Diseñé y lancé el sistema de reservaciones, la lógica de créditos de clases, listas de espera, cancelaciones, regalos, activaciones de eventos y herramientas de onboarding para estudios. Escalé la plataforma de 30 a más de 400 usuarios en sus primeros meses. Supervisé producto, ingeniería, alianzas y crecimiento de comunidad como CEO." },
    category: { en: "Product", es: "Producto" },
    categories: [
      { en: "React Native", es: "React Native" },
      { en: "Firebase", es: "Firebase" },
      { en: "GCP", es: "GCP" },
      { en: "Product Leadership", es: "Liderazgo de Producto" },
      { en: "Growth", es: "Crecimiento" },
    ],
    year: 2024,
    role: { en: "Co-Founder / CEO", es: "Co-Fundador / CEO" },
    cover: { src: "/projects/kodda-app.webp", width: 1280, height: 800 },
    coverAlt: { en: "Official Kodda iOS app screenshots from the App Store showing wellness programs and class bookings", es: "Screenshots oficiales de la app iOS de Kodda en el App Store mostrando programas de bienestar y reservas de clases" },
    gallery: [
      { src: "/projects/kodda-app.webp", width: 1280, height: 800 },
    ],
    links: { live: "https://apps.apple.com/mx/app/kodda/id6475354577" },
    featured: true,
  },
  {
    id: "apex",
    slug: "apex",
    title: { en: "Apex — Racing Line Optimizer", es: "Apex — Racing Line Optimizer" },
    summary: { en: "A browser tool that plots and compares racing lines lap by lap.", es: "Herramienta web que traza y compara líneas de carrera vuelta por vuelta." },
    description: { en: "I built Apex, a browser tool where you sketch a race track freehand, tune your car setup (F1, GT3, street, or kart), and it computes the optimal racing line — apexes, corner speeds, and braking points — using real vehicle physics.", es: "Construí Apex, una herramienta de navegador donde dibujas una pista a mano alzada, ajustas el setup del coche (F1, GT3, calle o kart) y calcula la línea de carrera óptima — apexes, velocidades de curva y puntos de frenado — con física vehicular real." },
    category: { en: "Web App", es: "Web App" },
    categories: [
      { en: "React", es: "React" },
      { en: "Canvas", es: "Canvas" },
      { en: "Physics Simulation", es: "Simulación Física" },
      { en: "Firebase Hosting", es: "Firebase Hosting" },
    ],
    year: 2025,
    role: { en: "Creator / Engineer", es: "Creador / Ingeniero" },
    cover: { src: "/projects/apex.webp", width: 1280, height: 800 },
    coverAlt: { en: "Apex web app showing the 'Draw your circuit' track editor next to car setup sliders and sample tracks", es: "App web Apex mostrando el editor de pistas 'Draw your circuit' junto a los controles de setup del coche y pistas de ejemplo" },
    gallery: [
      { src: "/projects/apex.webp", width: 1280, height: 800 },
    ],
    links: { live: "https://get-apex.web.app/", repo: "https://github.com/MikeAlvarado/getapex" },
    featured: true,
  },
  {
    id: "tequilaKaos",
    slug: "tequila-kaos",
    title: { en: "Tequila KAOS", es: "Tequila KAOS" },
    summary: { en: "Product and web consulting for a tequila brand, from strategy to launch.", es: "Consultoría de producto y web para una marca de tequila, de estrategia a lanzamiento." },
    description: { en: "I led the digital strategy and web experience for KAOS, a Mexican cinnamon–tequila liqueur brand (\"Licor de Canela al Tequila, Hecho en México\"). I guided the brand identity, UX, and website implementation so the online presence matched the premium, tradition-defying positioning of the product.", es: "Lideré la estrategia digital y la experiencia web de KAOS, una marca mexicana de licor de canela al tequila (\"Hecho en México\"). Guié la identidad de marca, el UX y la implementación del sitio para que la presencia en línea reflejara el posicionamiento premium y desafiante de la marca." },
    category: { en: "Consulting", es: "Consultoría" },
    categories: [
      { en: "Web Design", es: "Diseño Web" },
      { en: "Brand Strategy", es: "Estrategia de Marca" },
      { en: "React", es: "React" },
    ],
    year: 2024,
    role: { en: "Product & Web Consultant", es: "Consultor de Producto y Web" },
    cover: { src: "/projects/tequila-kaos.webp", width: 1280, height: 800 },
    coverAlt: { en: "Tequila KAOS website hero showing the KAOS bottle and the tagline 'Desafía la tradición'", es: "Hero del sitio de Tequila KAOS con la botella y el lema 'Desafía la tradición'" },
    gallery: [
      { src: "/projects/tequila-kaos.webp", width: 1280, height: 800 },
    ],
    links: { live: "https://tequilakaos.com/" },
    featured: true,
  },
  {
    id: "reactPractice",
    slug: "react-practice",
    title: { en: "React Lab", es: "React Lab" },
    summary: { en: "A working lab where I build and publish React patterns in the open.", es: "Un laboratorio donde construyo y publico patrones de React en abierto." },
    description: { en: "My playground for staying sharp with the modern React ecosystem — a growing showcase of self-contained exercises built with React 19, TypeScript, and Vite: a sign-up flow, Minesweeper, Snake, Wordle, and a mini SQL query engine that parses and runs SELECT queries against an in-memory table. Every exercise ships with a source panel that shows the actual logic files behind it.", es: "Construí React Practice para seguir practicando con el ecosistema moderno de React — son ejercicios independientes hechos con React 19, TypeScript y Vite: un flujo de registro, Minesweeper, Snake, Wordle y un mini motor de consultas SQL que interpreta y corre queries SELECT contra una tabla en memoria. Cada ejercicio tiene un panel donde puedes ver el código real detrás de la lógica." },
    category: { en: "Open Source", es: "Código abierto" },
    categories: [
      { en: "React", es: "React" },
      { en: "TypeScript", es: "TypeScript" },
      { en: "Vite", es: "Vite" },
    ],
    year: 2026,
    role: { en: "Frontend Engineer", es: "Ingeniero Frontend" },
    cover: { src: "/projects/react-practice-2.webp", width: 1290, height: 924 },
    coverAlt: { en: "React Practice component showcase listing the Register, Minesweeper, Snake, Wordle, and SQL query engine exercises", es: "Pantalla de inicio de React Practice mostrando los ejercicios Register, Minesweeper, Snake, Wordle y el motor de consultas SQL" },
    gallery: [
      { src: "/projects/react-practice-2.webp", width: 1290, height: 924 },
      { src: "/projects/react-practice.webp", width: 1290, height: 924 },
    ],
    links: { live: "https://react-practice-templates.web.app/", repo: "https://github.com/MikeAlvarado/react_practice" },
    featured: true,
  },
  {
    id: "lightcycleArena",
    slug: "lightcycle-arena",
    title: { en: "Lightcycle Arena", es: "Lightcycle Arena" },
    summary: { en: "A browser lightcycle game built for speed and tight controls.", es: "Juego de lightcycles en el navegador, hecho para velocidad y control preciso." },
    description: { en: "I built a retro TRON-style lightcycle game with React and TypeScript. It runs on a lattice-based grid that separates vertices from edges for precise trail collisions, with difficulty-scaled AI opponents, local highscore persistence, and an on-screen D-Pad for mobile. Playable in the browser.", es: "Construí un juego retro de lightcycles estilo TRON con React y TypeScript. Corre sobre una cuadrícula tipo lattice que separa vértices de aristas para colisiones precisas de estelas, con oponentes IA que escalan en dificultad, highscores locales y un D-Pad en pantalla para móvil. Jugable en el navegador." },
    category: { en: "Web Game", es: "Juego Web" },
    categories: [
      { en: "React", es: "React" },
      { en: "TypeScript", es: "TypeScript" },
      { en: "Game Dev", es: "Desarrollo de Juegos" },
      { en: "Firebase Hosting", es: "Firebase Hosting" },
    ],
    year: 2025,
    role: { en: "Game Developer", es: "Desarrollador de Videojuegos" },
    cover: { src: "/projects/lightcycle-arena.webp", width: 1280, height: 800 },
    coverAlt: { en: "Lightcycle Arena start screen with a glowing neon title, Start button, and Top 5 leaderboard", es: "Pantalla de inicio de Lightcycle Arena con título neón brillante, botón Start y tabla de Top 5" },
    gallery: [
      { src: "/projects/lightcycle-arena.webp", width: 1280, height: 800 },
    ],
    links: { live: "https://tron-lightcycle.web.app/", repo: "https://github.com/MikeAlvarado/lightcycle_arena" },
    featured: false,
  },
  {
    id: "yCombinator",
    slug: "y-combinator",
    title: { en: "Y Combinator – S21", es: "Y Combinator – S21" },
    summary: { en: "Kodda was accepted into Y Combinator's S21 batch.", es: "Kodda fue aceptada en el batch S21 de Y Combinator." },
    description: { en: "I co-founded Kodda, a digital health community selected for Y Combinator's Summer 2021 batch — guided wellness programs made by professionals, built from Monterrey, Mexico. YC gave me the full founder lifecycle: rapid iteration, pivots, and scaling operations.", es: "Cofundé Kodda, una comunidad de salud digital seleccionada para el batch de verano 2021 de Y Combinator — programas de bienestar guiados por profesionales, construida desde Monterrey, México. YC me dio el ciclo completo del fundador: iteración rápida, pivotes y escalamiento de operaciones." },
    category: { en: "Credential", es: "Credencial" },
    categories: [
      { en: "Startup", es: "Startup" },
      { en: "Leadership", es: "Liderazgo" },
      { en: "Product Strategy", es: "Estrategia de Producto" },
    ],
    year: 2021,
    role: { en: "Founder", es: "Fundador" },
    cover: { src: "/projects/y-combinator-kodda.webp", width: 1280, height: 800 },
    coverAlt: { en: "Kodda company profile on Y Combinator listing the Summer 2021 batch and founders", es: "Perfil de Kodda en Y Combinator mostrando el batch de verano 2021 y los fundadores" },
    gallery: [
      { src: "/projects/y-combinator-kodda.webp", width: 1280, height: 800 },
    ],
    links: { live: "https://www.ycombinator.com/companies/kodda" },
    featured: false,
  },
  {
    id: "pmp",
    slug: "pmp",
    title: { en: "PMP Certification", es: "Certificación PMP" },
    summary: { en: "Project Management Professional training, completed in 2025.", es: "Formación Project Management Professional, completada en 2025." },
    description: { en: "Completed Project Management Professional (PMP) formal training, strengthening execution frameworks, risk management, delivery planning, and cross-functional leadership. Complements technical engineering background with structured project delivery principles.", es: "Completé la formación formal de Project Management Professional (PMP), fortaleciendo frameworks de ejecución, gestión de riesgos, planeación de entregas y liderazgo multifuncional. Complementa mi formación técnica en ingeniería con principios estructurados de entrega de proyectos." },
    category: { en: "Credential", es: "Credencial" },
    categories: [
      { en: "Project Management", es: "Gestión de Proyectos" },
      { en: "Leadership", es: "Liderazgo" },
    ],
    year: 2025,
    role: { en: "Certification", es: "Certificación" },
    cover: { src: "/projects/pmp-certification.webp", width: 491, height: 347 },
    coverAlt: { en: "PMI-PMP training certificate of achievement issued to Miguel A Alvarado López by Gold Standard Certifications", es: "Certificado del entrenamiento PMI-PMP emitido a Miguel A Alvarado López por Gold Standard Certifications" },
    gallery: [
      { src: "/projects/pmp-certification.webp", width: 491, height: 347 },
    ],
    featured: false,
  },
  {
    id: "cloudFunctionsTs",
    slug: "cloud-functions-ts",
    title: { en: "Cloud Functions TS — Restaurant Orders API", es: "Cloud Functions TS — API de Órdenes de Restaurante" },
    summary: { en: "A typed Firebase Functions starter with the patterns I reach for.", es: "Base tipada de Firebase Functions con los patrones que uso siempre." },
    description: { en: "A REST API I built for managing restaurant orders (dine-in and takeaway) with TypeScript, Express, and Firebase Functions v2 — per-day sequential order numbers, strict order state transitions, and automatic payment syncing.", es: "Una REST API que construí para gestionar órdenes de restaurante (en mesa y para llevar) con TypeScript, Express y Firebase Functions v2 — números de orden secuenciales por día, transiciones de estado estrictas y sincronización automática de pagos." },
    category: { en: "Backend", es: "Backend" },
    categories: [
      { en: "TypeScript", es: "TypeScript" },
      { en: "Node.js", es: "Node.js" },
      { en: "Express", es: "Express" },
      { en: "Firebase Functions", es: "Firebase Functions" },
    ],
    year: 2025,
    role: { en: "Backend Engineer", es: "Ingeniero Backend" },
    cover: { src: "/projects/cloudfunctions-ts.webp", width: 1280, height: 800 },
    coverAlt: { en: "GitHub repository page for cloudfunctions-ts showing the Firebase Functions project structure", es: "Página del repositorio cloudfunctions-ts en GitHub mostrando la estructura del proyecto de Firebase Functions" },
    gallery: [
      { src: "/projects/cloudfunctions-ts.webp", width: 1280, height: 800 },
    ],
    links: { repo: "https://github.com/MikeAlvarado/cloudfunctions-ts" },
    featured: false,
  },
]
